language: python

services:
  - docker

script:
  - python3 unitests.py

after_success:
  - docker pull afdev9988/w2p
  - docker run --name bcove_build -p 443:443 -p 80:80 -d afdev9988/w2p:latest 
  - docker exec -it bcove_build /bin/bash -c ./applications/updater.sh
  - docker login hub.docker.com -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker commit bcove_build afdev9988/w2p:testing
  - docker push afdev9988/w2p:testing
  - docker rm bcove_build
