language: python

services:
  - docker

before_install:
  - docker pull afdev9988/w2p
  - docker run -d -p 127.0.0.1:80:80 afdev9988/w2p /bin/sh -c "ls"
  - docker ps -a
  - docker run afdev9988/w2p /bin/sh -c "ls"

script:
  - python3 unitests.py
